github: wyxos
patreon: wyxos
custom: ['https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-26T09192G3624650VMXHO6OA', 'Paypal 
subscription', 'https://www.paypal.com/paypalme/my/profile', 'Paypal one time']
